### ISSUE TITLE
Trocar de máscara de Cpf para Cnpj ao digitar

### ISSUE THREAD

**Issue by AlexPassos** [flutterbootcamp/brasil_fields#10]
Olá, como faço para ir digitando no campo e trocar a mascara de Cpf para Cnpj? É possível? Da uma ideia ai.

**Comment by rubensdemelo** [comment]
neste momento, ainda não é possível. Pois cada máscara possui um tamanho fixo. Mas dá pra criar uma mascara dinamica. é uma boa sugestão. quando implementar, eu fecho esta issue. obrigado

**Comment by rubensdemelo** [comment]
@AlexPassos atualiza para a versao 0.3.0 e testa o CpfOuCnpjFormatter
