### ISSUE TITLE
Bug no cursor

### ISSUE THREAD

**Issue by jfelipe72** [flutterbootcamp/brasil_fields#12]
O cursor está saindo do ponto X e voltando para o início, no ponto 0.

[Screenshot](https://prnt.sc/t3v3k0)

`TextFormField(
  inputFormatters: [
    WhitelistingTextInputFormatter.digitsOnly,
    CpfInputFormatter(),
  ],
);`

**Comment by rubensdemelo** [comment]
@jfelipe72  Pode postar o código completo? pq o aplicativo de exemplo tá funcionando sem erro.
![Jun-22-2020 13-24-08](https://user-images.githubusercontent.com/1351177/85311968-94050700-b48c-11ea-9c99-5fa3f28090b9.gif)

**Comment by rubensdemelo** [comment]
@jfelipe72 qual channel você tá usando ? stable, master ou dev ?

**Comment by jfelipe72** [comment]
Segue código completo:
[widget_teste.zip](https://github.com/rubensdemelo/brasil_fields/files/4834586/widget_teste.zip)

Desculpa, sou iniciante, mas a channel que você fala, é do Flutter, do git ou do package?

`dependencies:
  brasil_fields: ^0.2.0`

**Comment by jfelipe72** [comment]
![brasil_fieldsgif](https://user-images.githubusercontent.com/49200056/85811116-89b86680-b733-11ea-9661-be9022c94682.gif)

**Comment by guerrals** [comment]
Também estou enfrentando o mesmo problema. Utilizo o channel beta.

**Comment by jfelipe72** [comment]
> Também estou enfrentando o mesmo problema. Utilizo o channel beta.

Se você conseguir resolver, me avisa, por favor.

**Comment by rubensdemelo** [comment]
@guerrals e @jfelipe72 Utilizem o channel stable. Vcs estão usando o beta ou dev.

**Comment by jfelipe72** [comment]
> @guerrals e @jfelipe72 Utilizem o channel stable. Vcs estão usando o beta ou dev.

Realmente, acabei de ver aqui

**Comment by jfelipe72** [comment]
> @guerrals e @jfelipe72 Utilizem o channel stable. Vcs estão usando o beta ou dev.

Realmente, acabei de ver aqui

**Comment by jfelipe72** [comment]
> @guerrals e @jfelipe72 Utilizem o channel stable. Vcs estão usando o beta ou dev.

Realmente era isso, fiz a alteração e já funcionou aqui, eu estava utilizando o beta.
Muito obrigado, Rubens!

Após trocar o channel de beta para stable, deu um problema e eu não conseguia rodar o app. Se acontecer com alguém, é só reinstalar o plug-in do Dart e do Flutter (utilizo o VS Code), depois disso funcionou normalmente.
