### ISSUE TITLE
CEP não se costuma usar ponto

### ISSUE THREAD

**Issue by ir4ever** [flutterbootcamp/brasil_fields#16]
CEP não se costuma usar ponto poderiam ter um cep sem ponto que ficaria perfeito.

**Comment by jfelipe72** [comment]
Você pode fazer a modificação do fonte no seu projeto e retirar o ponto.

**Comment by jfelipe72** [comment]
> CEP não se costuma usar ponto poderiam ter um cep sem ponto que ficaria perfeito.

Você pode mudar o fonte do package no seu projeto e retirar o ponto.

**Comment by rubensdemelo** [comment]
@Raphael-Jose-Ferraro-IRForever vou adicionar um atributo para ter a opção do ponto ou não. Obrigado pela sugestao.

**Comment by ir4ever** [comment]
Muito obg!!! Ajuda bastante! Eu tinha alterado o arquivo como recomendou. Vcs estao de parabens!

**Comment by RhogHub** [comment]
Eu removi o ponto do font e o carriage do cursor ficou bugado.

Alguma sugestão?


Quanto ao resto, a lib esta de parabéns muito útil.

**Comment by ir4ever** [comment]
Meu if do ponto ficou assim e funcionou.
if(newTextLength >=3){
newText.write(newValue.text.substring(0,usedSubstringIndex =2) + '');

**Comment by RhogHub** [comment]
> Meu if do ponto ficou assim e funcionou.
> if(newTextLength >=3){
> newText.write(newValue.text.substring(0,usedSubstringIndex =2) + '');

Eu havia apenas removido o ponto do + ''); 

Agora funcionou!

Show, muito obrigado Raphael.

**Comment by ir4ever** [comment]
Nice man. Eh noiz!

**Comment by rubensdemelo** [comment]
Agora na v0.5.0 tem o parametro `ponto`. Para habilitar/desabilitar o ponto na máscara. É só setar ele como `false` ou `true` (que é o default).

**Comment by EvincarSN** [comment]
> Agora na v0.5.0 tem o parametro `ponto`. Para habilitar/desabilitar o ponto na máscara. É só setar ele como `false` ou `true` (que é o default).

Maravilha!

obs: O título no pub.dev esta "brasil_fields 0.6.0 ".


Abraço!
