### ISSUE TITLE
Iniciar widget com valor inicial formatado

### ISSUE THREAD

**Issue by marcoprodata** [flutterbootcamp/brasil_fields#17]
Mestre, como faço pra iniciar o widget já preenchido e formatado? 

Desde já agradeço a atenção recebida.

**Comment by rubensdemelo** [comment]
@marcoprodata tem sim. vou postar o código aqui.

**Comment by marcoprodata** [comment]
Mestre, vai postar aqui mesmo na resposta ou como exemplo?

**Comment by rubensdemelo** [comment]
@marcoprodata vou sim. Fica tranquilo. E também adicionar na documentação.

**Comment by marcoprodata** [comment]
Ótimo, muito obrigado.

**Comment by GManzke** [comment]
fala @rubensdemelo ! Tudo certo? Ví que ainda não postou atualização sobre essa issue, essa atualização ainda está por vir?

**Comment by rubensdemelo** [comment]
@GManzke e @marcoprodata vai sair sim. Hoje ou amanhã.

**Comment by rubensdemelo** [comment]
@GManzke e @marcoprodata vejam a versão 4.0. Já tem os métodos e como iniciar um campo de texto com o valor formatado.

**Comment by marcoprodata** [comment]
Mestre, vi que criou a UtilData pra pegar a Data formatada, e com relação aos outros formatos? Fone, CPF, CNPJ, CEP?

**Comment by rubensdemelo** [comment]
@marcoprodata vou providenciar. deixa cmg

**Comment by chrystoffer** [comment]
Estava com o mesmo problema e resolvi utilizando o pacote StringMask
Instancio ele com a mascara que desejo: (cpf exemplo)
`StringMask _cpfMask = new StringMask('000.000.000-00');`
E depois para preencher o campo ao abrir a tela
`_cpfController.text = _cpfMask.apply(model.cpf) ?? '';`

Funciona perfeitamente caso alguém precise.


E parabéns ao pacote brasil_fields, utilizo em todos meus projetos :D

**Comment by rubensdemelo** [comment]
Desculpa pela demora pessoal. Em breve vou postar um guia de como conseguir isso. Estou terminando uma nova versao do pacote, com outros formatters.

**Comment by rubensdemelo** [comment]
Teremos algo assim: 

```UtilBrasilFields.obterCpf('11122233344')```

E o retorno será o campo já formatado. O que vcs acham ?

**Comment by marcoprodata** [comment]
Por mim fica perfeito

**Comment by rubensdemelo** [comment]
Agora na v0.5.0 temos os métodos:

`
UtilBrasilFields.obterCpf`, `UtilBrasilFields.obterCnpj`e `UtilBrasilFields.obterCep`.

Caso precisem de mais algum, só postar aqui.

**Comment by ArthurBergamo** [comment]
Poderia sobrescrever o metodo:
`override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    // Your validations/formats
    return null;
  }`
da classe TextInputFormatter, ai daria pra utilizar dessa maneira, para o valor inicial já vir formatado:
`TextFormField(
            initialValue: MyFormater.defaultFormat(someString),
            inputFormatters: [MyFormater()],
          )`
Estou precisando do Telefone.
Muito Obrigado

**Comment by rubensdemelo** [comment]
@ArthurBergamo mas este método já é sobrescrito em cada um dos formatters.

**Comment by marcoprodata** [comment]
Não faltou o obterFone?

**Comment by rubensdemelo** [comment]
@marcoprodata  Já estou implementando. Vai ficar assim:

`UtilBrasilFields.obterTelefone('00999998877')` = '(00) 99999-8877)

`UtilBrasilFields.obterTelefone('999998877', ddd=false)` = ('99999-8877)

**Comment by ArthurBergamo** [comment]
@marcoprodata, encontrei nesse tópico a solução pra um problema que eu estava tendo.
[https://stackoverflow.com/questions/53960797/is-there-a-way-for-inputformatters-on-a-textformfield-to-be-executed-when-the-fo](url)
eu tinha explicado errado, é um método estático igual você fez na classe UtilBrasilFields.

**Comment by marcoprodata** [comment]
> @marcoprodata Já estou implementando. Vai ficar assim:
> 
> `UtilBrasilFields.obterTelefone('00999998877')` = '(00) 99999-8877)
> 
> `UtilBrasilFields.obterTelefone('999998877', ddd=false)` = ('99999-8877)

Não teria como ao invés de ter esse parametro "ddd=false", testar o tamanho da string e retornar o formato de acordo com o tamanho?

**Comment by rubensdemelo** [comment]
> https://stackoverflow.com/questions/53960797/is-there-a-way-for-inputformatters-on-a-textformfield-to-be-executed-when-the-fo

Agora entendi. Obrigado. Por enquanto, vou deixar na `UtilBrasilFields` pois essa funcionalidade pode ser utilizada em outros lugares que não apenas em TextField.

**Comment by rubensdemelo** [comment]
A versão 0.6.0 já tem os métodos e a documentação necessária para iniciar o valor de textfields já formatados.
