### ISSUE TITLE
Poderia incluir máscaras de medidas?

### ISSUE THREAD

**Issue by RogerBrusamarello** [flutterbootcamp/brasil_fields#19]
Poderia ser incluído no pacote, mascáras de medidas tipo centímetros, metros, milímetros e quilomêtros?
Ex: 120,00 mm, 80,00 mm, 12,00 m, 80 km, 10,00 cm.
(Acredito que não precisa das unidade "mm/km/cm" na máscara apenas o auto ajuste das vírgulas)

**Comment by rubensdemelo** [comment]
@RogerBrusamarello ótima sugestão. Obrigado, vou implementar.

**Comment by rubensdemelo** [comment]
A versão 0.6.0 já tem os formatters solicitados. Abs
