### ISSUE TITLE
Utilizar inglês como linguagem padrão

### ISSUE THREAD

**Issue by raafvargas** [flutterbootcamp/brasil_fields#21]
É comum que times acabem optando por utilizar inglês como linguagem padrão de desenvolvimento. Seria interessante padronizar para inglês os nomes de classes, variáveis e arquivos utilizadas no projeto também.

Exemplos:
* `HoraInputFormatter`
* `formatter/cartao_bancario_input_formatter.dart`

**Comment by rubensdemelo** [comment]
Toda a documentação, código e comentários está em pt-br. Eu mesmo, em todos os meus projetos adoto o ingles, mas para o packages, decidi manter tudo em nossa lingua nativa.
