### ISSUE TITLE
Erro na formatação de data

### ISSUE THREAD

**Issue by eduardotq** [flutterbootcamp/brasil_fields#23]
Olá, estou tendo um erro no DataInputFormatter(). Quando começo a digitar, a partir do 3º caractere, o formatter começa a inserir barras a mais. Depois disso até o ato de tentar apagar as barras, faz ele inserir outras e o input fica todo desformatado.
O erro também ocorre com o formatador de cpf e cep, mas não acontece se for adicionado um formatter de digits only. 

` inputFormatters: [
                                  FilteringTextInputFormatter.digitsOnly,
                                  CpfInputFormatter(),
                                ],`

Deste modo com o cpf, funciona corretamente, mas se eu adiciono o digitsonly no campo de date, ele não formata nada.

Outros pacotes de formatação de data funcionam, mas eu não queriar ter que usar um outro pacote só pra formatar a data. Existe alguma maneira de contornar esse problema?

Estou utilizando o Channel stable, 1.22.2

[
![Screenshot_1603719233](https://user-images.githubusercontent.com/65795387/97179319-6fd96f80-1777-11eb-9f3b-6eb7b2082a34.png)
](url)

**Comment by rubensdemelo** [comment]
@eduardotq qual o channel do flutter vc está usando ? Pode posta o código completo, por favor.

**Comment by eduardotq** [comment]
Estou utilizando o Channel stable, 1.22.2

```
Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (2 weeks ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2
```

```
TextFormField(
                                autofocus: true,
                                decoration: InputDecoration(
                                  labelText: "CPF",
                                  border: themeData.inputDecorationTheme.border,
                                  enabledBorder:
                                      themeData.inputDecorationTheme.border,
                                  focusedBorder: themeData
                                      .inputDecorationTheme.focusedBorder,
                                  prefixIcon: Icon(MdiIcons.cardAccountDetails,
                                      size: 24),
                                ),
                                keyboardType: TextInputType.number,
                                inputFormatters: [
                                  FilteringTextInputFormatter.digitsOnly,
                                  CpfInputFormatter(),
                                ],
                                onChanged: (value) {
                                  _.cpf = value;
                                },
                                validator: (value) {
                                  if (GetUtils.isCpf(value)) {
                                    return null;
                                  } else
                                    return 'CPF inválido';
                                },
                                textInputAction: TextInputAction.next,
                                onFieldSubmitted: (value) {
                                  FocusScope.of(context)
                                      .requestFocus(_.nameTextFocusNode);
                                },
                              )
```
No caso do cpf, funciona com o `FilteringTextInputFormatter.digitsOnly,`

Já no caso do TextFormField de data de nascimento, se utilizar o `FilteringTextInputFormatter.digitsOnly`, não funciona. E sem ele, fica com aquele problema citado acima.

```
TextFormField(
                                  focusNode: _.birthTextFocusNode,
                                  decoration: InputDecoration(
                                    hintText: 'dd/mm/aaaa',
                                    labelText: "Nascimento",
                                    border:
                                        themeData.inputDecorationTheme.border,
                                    enabledBorder:
                                        themeData.inputDecorationTheme.border,
                                    focusedBorder: themeData
                                        .inputDecorationTheme.focusedBorder,
                                    prefixIcon: Icon(
                                      MdiIcons.calendarBlankOutline,
                                      size: 24,
                                    ),
                                  ),
                                  onChanged: (value) {
                                    _.birth = value;
                                  },
                                  keyboardType: TextInputType.number,
                                  inputFormatters: [
                                    DateInputFormatter(),
                                    //DataInputFormatter()
                                  ],
                                  onFieldSubmitted: (value) {
                                    FocusScope.of(context).requestFocus(
                                      _.motherNameTextFocusNode,
                                    );
                                  },
                                  textInputAction: TextInputAction.next,
                                ),
```

**Comment by rubensdemelo** [comment]
beleza. vou testar aqui

**Comment by rubensdemelo** [comment]
@eduardotq Teste esse código e veja se funciona. 

```
import 'package:brasil_fields/brasil_fields.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Brasil Fields',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Brasil Fields'),
        ),
        body: TextFormField(
          inputFormatters: [
            FilteringTextInputFormatter.digitsOnly,
            DataInputFormatter(),
          ],
        ),
      ),
    );
  }
}

```

**Comment by eduardotq** [comment]
Realmente, deste modo funcionou

**Comment by eduardotq** [comment]
No arquivo original, utilizando o pacote pattern_formatter, funciona normalmente então não sei o que poderia ser, se é algum problema de compatibilidade com alguma configuração do meu projeto outra coisa. Essa issue pode continuar aberta ou posso fechá-la?

**Comment by andersonrieper** [comment]
Olá Rubens . Passo EXATAMENTE pelo mesmo problema!! O que exatamente preciso fazer em MEU código para que a formatação seja mostrada de forma correta?

Segue abaixo código que uso para o campo DATA DE NASCIMENTO:

            TextFormField(
              keyboardType: TextInputType.datetime,
              decoration: InputDecoration(
                  labelText: "Data de Nascimento:",
                  labelStyle: TextStyle(
                    color: Colors.black,
                    fontSize: 26
                  ),
                hintText: "Informe sua DATA DE NASCIMENTO. Ex: 24/04/1985",
                hintMaxLines: 3,
              ),
                inputFormatters: [
                DataInputFormatter(),
              ],
              controller: var_Data_Nascimento,
            ),

Precisei usar uma versão da dependência bem inferior:
brasil_fields: ^0.6.1             # Habilita campos em formato brasileiro...

Pois quando tento usar uma versão de dependência mais atual, recebo erro abaixo quando executo PUB GET:

"The current Dart SDK version is 2.10.3.

Because projeto_cupido_adventista depends on brasil_fields >=1.0.0-nullsafety.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed."

**Comment by rubensdemelo** [comment]
@andersonrieper Atualiza a versão do package e utiliza o formatter  FilteringTextInputFormatter.digitsOnly, conforme orientação da documentação:

```
TextFormField(
  inputFormatters: [
    FilteringTextInputFormatter.digitsOnly,
    CepInputFormatter(),
  ],
);
```

**Comment by andersonrieper** [comment]
NÃO posso atualizar para a versão 1.1.2, pois acusa o erro de "versão inválida do Dart", como eu havia mencionado em minha postagem.

Abaixo repasso novamente a mensagem de erro que recebo ao tentar usar a versão 1.1.2 do pacote:

"Precisei usar uma versão da dependência bem inferior:
brasil_fields: ^ 0.6.1 # Habilita campos em formato brasileiro ...

Pois quando tento usar uma versão de dependência mais atual, recebo erro abaixo quando executo PUB GET:

"A versão atual do Dart SDK é 2.10.3.

Como projeto_cupido_adventista depende de brasil_fields> = 1.0.0-nullsafety.0 que requer a versão do SDK> = 2.12.0-0 <3.0.0, a resolução da versão falhou. "

**Comment by fogaiht** [comment]
@andersonrieper tenta deixar fixa a versão do package, no lugar de 'brasil_fields: ^ 0.6.1' coloca 'brasil_fields: 0.6.1'

**Comment by rubensdemelo** [comment]
A versão 1.+ do package está em null safety e precisa do dart sdk 2.12, por isso você nao consegue migrar.

Mantenha a versao 0.6+ e utilize o formatter `FilteringTextInputFormatter.digitsOnly`

**Comment by andersonrieper** [comment]
> @andersonrieper tenta deixar fixa na versão do pacote, no lugar de 'brasil_fields: ^ 0.6.1' coloca 'brasil_fields: 0.6.1'

Adaptei o código conforme sua orientação, mas erro persiste... :-(

**Comment by andersonrieper** [comment]
> A versão 1. + do package is in null safety e precisa do dardo sdk 2.12, por isso você não consegue migrar.
> 
> Mantenha a versão 0.6+ e utilize o formatador `FilteringTextInputFormatter.digitsOnly`

Mantive a versão 0.6+, porém recebo a mensagem abaixo quando tento utilizar a propriedade "digitsOnly":

lib/main.dart:114:17: Error: The getter 'FilteringTextInputFormatter' isn't defined for the class '_PrincipalState'.
 - '_PrincipalState' is from 'package:projeto_cupido_adventista/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FilteringTextInputFormatter'.

Checando as instruções de instalação do pacote, não faz qualquer menção da necessidade em declarar algum "Getter" na classe principal do Projeto...

**Comment by rubensdemelo** [comment]
Use o digitOnly da classe https://api.flutter.dev/flutter/services/WhitelistingTextInputFormatter-class.html

**Comment by andersonrieper** [comment]
> Use o digitOnly da classe https://api.flutter.dev/flutter/services/WhitelistingTextInputFormatter-class.html

Ao tentar conhecer a classe, consta a informação abaixo:

![image](https://user-images.githubusercontent.com/85019515/120358974-859aae80-c2dd-11eb-967a-f701ed8e29d0.png)

Ou seja, já encontra-se obsoleta para uso no Flutter...

:-(

**Comment by rubensdemelo** [comment]
Sim, eu sei. Mas esta é a versão compatível com a versão do package e do flutter que vc está usando (que tb estão obsoleta).

**Comment by andersonrieper** [comment]
> Use o digitOnly da classe https://api.flutter.dev/flutter/services/WhitelistingTextInputFormatter-class.html

Descobri uma solução para o problema, SEM precisar usar a classe obsoleta acima.

Na seção INSTALANDO, consta a seguinte instrução:
![image](https://user-images.githubusercontent.com/85019515/120478111-e29c7000-c382-11eb-94ed-4bc4509cbfa4.png)

Na verdade, é preciso TAMBÉM que conste a instrução abaixo:
import 'package:flutter/services.dart';

Com essa instrução adicional acima o pacote brasil_fields funciona 100% (muitos desenvolvedores auto-didatas certamente também desconhecem desse pequeno detalhe...)

Fica então a sugestão para atualizar a seção INSTALANDO para o pacote "services.dart" (que é absolutamente NECESSÁRIO para que o brasil_fields realmente funcione!!) 

E agradeço de antemão por toda a atenção dispensada!! Ajudou-me muito em encontrar a solução!! :-D Grato!!!

**Comment by rubensdemelo** [comment]
O package services.dart contém os formatters, tanto o novo (Filtering...) como o obsoleto (Whitelisting...). 

Portanto, ao importar qualquer um dos formatters, este package ja é importado automaticamente.

Boa sorte com o projeto 👍 .
