### ISSUE TITLE
Mask de placa de carros, agência de banco e número de conta de banco

### ISSUE THREAD

**Issue by diegopereira99** [flutterbootcamp/brasil_fields#27]
Essas mask são muito utilizadas, seria legal serem implementadas.

**Comment by rubensdemelo** [comment]
Otimas sugestoes. Vou implementar. Obrigado

**Comment by diegopereira99** [comment]
Aguardo anciosamente rsrs. Vlw!

**Comment by rubensdemelo** [comment]
Place de carro tem uma "limitação", por permitir o uso de letras e números. Vou pensar em alguma maneira de deixar o formatter dinamico.

**Comment by diegopereira99** [comment]
Demoro!

**Comment by rubensdemelo** [comment]
Para placas de carro já foi implementado.

Para agencia bancária e conta não é o mesmo padrão para todos os bancos:

https://imobiliarias.superlogica.com/hc/pt-br/articles/360042873194-Padrão-de-contas-bancárias-Split-de-pagamentos
