### ISSUE TITLE
Incompativel com flutter_localizations

### ISSUE THREAD

**Issue by billbarsch** [flutterbootcamp/brasil_fields#28]
está dando esse erro aqui ao tentar instalar:

Because no versions of brasil_fields match >0.6.0 <0.7.0 and brasil_fields 0.6.0 depends on intl ^0.16.1, brasil_fields ^0.6.0 requires intl ^0.16.1.
And because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, brasil_fields ^0.6.0 is incompatible with flutter_localizations from sdk.
So, because maisagil depends on both flutter_localizations any from sdk and brasil_fields ^0.6.0, version solving failed

-----------------------------------------

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  brasil_fields: ^0.6.0
  searchable_dropdown: ^1.1.3
  http: ^0.12.2 
  path: ^1.7.0
  path_provider: ^1.1.0
  sqflite: ^1.1.5
  ffi: ^0.1.3
  sqflite_common_ffi: ^1.1.1
  idb_sqflite: ^0.3.2+1
  font_awesome_flutter: ^8.4.0
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  base32: ^1.1.2

**Comment by billbarsch** [comment]
eu removi a versão 0.6.0 do brasil_fields dai resolveu 
----------------------------------------------
dependencies:
flutter:
sdk: flutter
flutter_localizations:
sdk: flutter
brasil_fields:       <-------------------
searchable_dropdown: ^1.1.3
http: ^0.12.2

**Comment by billbarsch** [comment]
acabei de perceber que ele instalou a versão 0.3.2
então não ficou legal
parece que a versão 0.6.0 não é compativel com o flutter_localizations mesmo

**Comment by rubensdemelo** [comment]
tenta indicar a versao ^0.16.1 do `flutter_localizations`. Se vc estiver usando a versao mais recente, com null safety, vai dar este erro mesmo.

**Comment by billbarsch** [comment]
agora deu certo fazendo assim:
(instalou a versão 0.6.0!!!! obrigado)
---------------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  **brasil_fields: ^0.6.0**
  searchable_dropdown: ^1.1.3
  http: ^0.12.2 
  path: ^1.7.0
  path_provider: ^1.1.0
  sqflite: ^1.1.5
  ffi: ^0.1.3
  sqflite_common_ffi: ^1.1.1
  idb_sqflite: ^0.3.2+1
  font_awesome_flutter: ^8.4.0
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  base32: ^1.1.2

**dependency_overrides:
  intl: ^0.17.0-nullsafety.2**

**Comment by rubensdemelo** [comment]
Excelente.
