### ISSUE TITLE
Pedido de adição

### ISSUE THREAD

**Issue by ir4ever** [flutterbootcamp/brasil_fields#31]
Queria agradecer o bom trabalho com esse pacote incrivel, queria recomendar, se possivel, uma adição na parte de moedas no RealInputFormater. Quando o usuario começar a digitar endereçar esse numero como centavos.
Por exemplo, digitando 2 digitos apresentar 0,xx ou um digito 0,0x. A partir do 3 ser x,xx ...
Mais uma vez parabens pelo pacote!

**Comment by rubensdemelo** [comment]
Já existe esta opção: o parametro `centavos`.
