### ISSUE TITLE
Erro no pubspec

### ISSUE THREAD

**Issue by ir4ever** [flutterbootcamp/brasil_fields#37]
Estou recebendo esse erro no pubspec.yaml

Flutter (Channel beta, 1.26.0-17.8.pre, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.26.0-17.8.pre at /development/flutter
    • Framework revision 044f2cf560 (2 days ago), 2021-02-24 13:02:05 -0800
    • Engine revision 042c82b02c
    • Dart version 2.12.0 (build 2.12.0-259.16.beta)

Because brasil_fields >=0.4.0 <1.0.0-nullsafety.0 depends on intl ^0.16.1 and rise_delivery depends on intl ^0.17.0, brasil_fields >=0.4.0 <1.0.0-nullsafety.0 is forbidden.
So, because rise_delivery depends on brasil_fields ^0.6.1, version solving failed.
pub get failed (1; So, because rise_delivery depends on brasil_fields ^0.6.1, version solving failed.)

**Comment by rubensdemelo** [comment]
Vc está usando qual channel ? stable ou master ?
