### ISSUE TITLE
Obs: Métodos para obter os valores CPF e CPNJ não estão sendo formatados

### ISSUE THREAD

**Issue by Yan22Oliveira** [flutterbootcamp/brasil_fields#41]
Boa tarde!

Os  métodos para obter os valores do CPF e CPNJ não estão sendo formatados como mostra na descrição do package.

Não sei se deixaram de adicionar essas funcionalidades depois da atualização, ou se esqueceram de corrigir a descrição.

Mas, só passando esse erro como observação para vocês. Fora isto, excelente pacote! 

brasil_fields: 1.1.1

UtilBrasilFields.obterCpf('11122233344') (111.222.333-44)
UtilBrasilFields.obterCnpj('11222333444455') (11.222.333/4444-55)

**Comment by rubensdemelo** [comment]
Obrigado. Vou corrigir.

**Comment by fabiowaga** [comment]
Confirmando, está funcionando até a versão 1.0.0, após isso, não retorna formatado.

**Comment by rubensdemelo** [comment]
@Yan22Oliveira e @fabiowaga podem me ajudar a reproduzir este erro? Estou testando e aparentemente está tudo funcionando bem: 

Criei um novo projeto com o código:

```dart
import 'package:brasil_fields/brasil_fields.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final _textController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Brasil Fields',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Brasil Fields'),
        ),
        body: Container(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: Center(
            child: TextField(
              controller: _textController,
              textAlign: TextAlign.center,
              style: const TextStyle(fontSize: 50),
              inputFormatters: [
                FilteringTextInputFormatter.digitsOnly,
                CpfInputFormatter(),
              ],
            ),
          ),
        ),
        floatingActionButton: FloatingActionButton(onPressed: () {
          print(UtilBrasilFields.obterCpf(_textController.text));
        }),
      ),
    );
  }
}
```

**Comment by rubensdemelo** [comment]
Encontrei o erro:

https://github.com/rubensdemelo/brasil_fields/commit/3fd9727bc708d6e3f224b13231bce2502c887a06#diff-f83957a1a207a0825859e96ee5a0712ffb87327edee91c46503ae537a27f3009

Vou reverter e mudar o nome dos métodos. Foi desatenção ao aceitar o PR.

**Comment by Yan22Oliveira** [comment]
Sim, eu tinha visto mesmo que você tinha comentado essa parte do código kkkk

**Comment by rubensdemelo** [comment]
Nova versão publicada para corrigir este ero: 1.1.2

**Comment by EndersonSS** [comment]
Olá, atualizei para a nova versão postada ontem para obter os valores do CPF e CPNJ. Mas um erro ainda persiste ao utilizar UtilBrasilFields.obterCnpj :

![image](https://user-images.githubusercontent.com/39202278/121428569-570b7c00-c94c-11eb-9998-469034e8537d.png)
o erro que recebo:

![image](https://user-images.githubusercontent.com/39202278/121428627-68548880-c94c-11eb-95c0-0194dc2df14f.png)
obs o UtilBrasilFields.obterCpf funciona normalmente.

**Comment by fogaiht** [comment]
> Olá, atualizei para a nova versão postada ontem para obter os valores do CPF e CPNJ. Mas um erro ainda persiste ao utilizar UtilBrasilFields.obterCnpj :
> 
> ![image](https://user-images.githubusercontent.com/39202278/121428569-570b7c00-c94c-11eb-9998-469034e8537d.png)
> o erro que recebo:
> 
> ![image](https://user-images.githubusercontent.com/39202278/121428627-68548880-c94c-11eb-95c0-0194dc2df14f.png)
> obs o UtilBrasilFields.obterCpf funciona normalmente.

o CNPJ que vc colocou: 11222333444455 deve ser válido para ele retornar com a máscara

teste um site excelente para gerar CNPJ, CPF e outros dados para testes
https://www.4devs.com.br/gerador_de_cnpj

**Comment by EndersonSS** [comment]
> > Olá, atualizei para a nova versão postada ontem para obter os valores do CPF e CPNJ. Mas um erro ainda persiste ao utilizar UtilBrasilFields.obterCnpj :
> > ![image](https://user-images.githubusercontent.com/39202278/121428569-570b7c00-c94c-11eb-9998-469034e8537d.png)
> > o erro que recebo:
> > ![image](https://user-images.githubusercontent.com/39202278/121428627-68548880-c94c-11eb-95c0-0194dc2df14f.png)
> > obs o UtilBrasilFields.obterCpf funciona normalmente.
> 
> o CNPJ que vc colocou: 11222333444455 deve ser válido para ele retornar com a máscara
> 
> teste um site excelente para gerar CNPJ, CPF e outros dados para testes
> https://www.4devs.com.br/gerador_de_cnpj

Ahh Beleza. Obrigado !!

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf
