### ISSUE TITLE
Novo formatter - Temperatura

### ISSUE THREAD

**Issue by RogerBrusamarello** [flutterbootcamp/brasil_fields#42]
Seria interresante o formatter de Temperatura. Acho que ajudaria bastante no desenvolvimento.

**Comment by rubensdemelo** [comment]
E qual o padrão do formato ?  

`37,9 `

**Comment by RogerBrusamarello** [comment]
Isso, hoje estava -4,8 ºC.

**Comment by rubensdemelo** [comment]
Mas o `ºC` não irá compor o formatter.

**Comment by RogerBrusamarello** [comment]
Isso, seria apenas o valor.
