### ISSUE TITLE
Capturar valores sem a mascara 

### ISSUE THREAD

**Issue by tattivitorino** [flutterbootcamp/brasil_fields#43]
Rubens, muito bom o seu package! 
Apenas senti falta de um método para recuperar os valores sem a mascara. Meu backend salva tudo "cru"..

**Comment by tattivitorino** [comment]
Na verdade eu acabei achando lendo o código.. acho que vale mencionar na documentação:
UtilBrasilFields.removeCaracteres(value);

:)

**Comment by rubensdemelo** [comment]
@tattivitorino Obrigado pela sugestão.

**Comment by tattivitorino** [comment]
@rubensdemelo também pude ver na IDE do VSCode que vc documentou que o mascara:false retorna o valor sem mascara.. isso seria melhor ainda para mencionar na documentação! 
E novamente obrigada pelo package! :))))
