### ISSUE TITLE
Exemplo das classes PADRÕES não está funcionando...

### ISSUE THREAD

**Issue by andersonrieper** [flutterbootcamp/brasil_fields#45]
Na seção README consta um código exemplo que demonstra como chamar as diferentes classes padrões oferecidas pelo pacote.

Porém, ao tentar usar o código exemplo mencionado em README (código segue abaixo), percebi que em meu projeto o botão Drop Down é mostrado de forma estranha, conforme print de tela que informo abaixo:

DropdownButton(
  items: Regioes.listaRegioes.map((String opcao) {
    return DropdownMenuItem<String>(
    value: opcao,
    child: Text(opcao),
  );
}).toList(),

![21](https://user-images.githubusercontent.com/85019515/120791470-a3992680-c50a-11eb-91b6-f3e24ffc2440.jpg)

Perceba que aparece um minúsculo "." na interface do app sinalizando que ali era para ser mostrado o Drop Down, porém a lista não é mostrada!

O QUE FALTA SER INCLUÍDO NO CÓDIGO EXEMPLO para que apareça a lista na interface?

**Comment by rubensdemelo** [comment]
Para habilitar o botao, precisa informar uma função no parametro `onChanged`:

onChanged: (opcao) {},

Vou corrigir e enviar uma nova versão. Obrigado.

**Comment by rubensdemelo** [comment]
Disponível na versão 1.1.3
