### ISSUE TITLE
bug na mascara de cpf e cnpj

### ISSUE THREAD

**Issue by marcoazevedo01** [flutterbootcamp/brasil_fields#47]
Olá estou tentando usar o package, porem quando ele começa a mostrar a mascara não deixa eu digitar todo o dado conforme a imagem e quando termina ele congela o campo e não deixa apagar.

![Untitled](https://user-images.githubusercontent.com/37423042/127343312-7a631679-c8bc-4a87-ad68-1efa03dcc8b1.png)

`flutter doctor
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [versÃ£o 10.0.21354.1], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code (version 1.58.2)
[√] Connected device (4 available)

• No issues found!`

**Comment by rubensdemelo** [comment]
Qual é o código ? Está usando o `FilteringTextInputFormatter.digitsOnly` ?

**Comment by marcoazevedo01** [comment]
Resolveu... achei que o formatter era opcional 😅

**Comment by ArthurFleischman** [comment]
estou tendo o mesmo problema do @marcoazevedo01, nao consigo usar.
