### ISSUE TITLE
Aceitar mais de 2 decimais no componente

### ISSUE THREAD

**Issue by jaimesakai** [flutterbootcamp/brasil_fields#48]
Parabéns pelo componente, já está me ajudando bastante. 
Li a documentação e não encontrei opção de configurar mais que 2 decimais. Exemplo o preço de combustivel 5,329 e também tem preços que tem muitas decimais R$ 112,456789.
Teria como parametrizar para aceitar mais decimais ?
Obrigado !

**Comment by rubensdemelo** [comment]
Teria sim. Vou parametrizar e libero uma nova versão. Obrigado pela sugestao

**Comment by perez-danilo** [comment]
Adicionado uma PR para este caso #51

**Comment by perez-danilo** [comment]
@jaimesakai creio que podemos fechar o issue

**Comment by rubensdemelo** [comment]
@perez-danilo Exatamente. Obrigado pela contribuição. Vou liberar uma nova versao do package amanha.
