### ISSUE TITLE
Alteração Formatter para placa de veículos

### ISSUE THREAD

**Issue by renehw** [flutterbootcamp/brasil_fields#52]
Olá! Este pacote é muito bom, me ajuda muito em varias partes do meu código, meus parabéns.

Gostaria de pedir que verifique fazer uma inclusão no formatter de placas, atualmente seu package tem suporte para as placas antigas, AAA-1234 e também para as placas do mercosul, AAA-1A23, contudo existe outro formato, AAA-12A3, neste caso a letra está presente no sexto caractere.

Qualquer dúvida estou a disposição.

**Comment by lstonussi** [comment]
obrigado

**Comment by rubensdemelo** [comment]
O formatter já foi ajustado e o README foi atualizado

`PlacaVeiculoInputFormatter() (atenção: nao utilizar FilteringTextInputFormatter.digitsOnly)`
