### ISSUE TITLE
Deletar R$  em RealInputFormatter

### ISSUE THREAD

**Issue by rubensdemelo** [flutterbootcamp/brasil_fields#53]
No RealInputFormatter, quando o parametro `moeda=true`, deve-se deletar o símbolo `R$`

![image](https://user-images.githubusercontent.com/1351177/141301542-1d5ea916-4031-4d4e-88cc-b0da3a7e80dc.png)

**Comment by BenevidesLecontes** [comment]
E relacionado a isso, o texto R$ devia ser opcional

**Comment by rubensdemelo** [comment]
> E relacionado a isso, o texto R$ devia ser opcional

E ele é. O parâmetro `moeda` adiciona o símbolo ou não. E por default, ele é false

**Comment by rubensdemelo** [comment]
Disponível na versão 1.3.0.

**Comment by BenevidesLecontes** [comment]
@rubensdemelo mas se for moeda false, ele n formata como moeda, pelo que eu pude testar. Pelo menos não adiciona os centavos, como era em versões anteriores.

**Comment by rubensdemelo** [comment]
@BenevidesLecontes mas agora tem o `CentavosInputFormatter`, somente para estes casos. E com o parametro `moeda`.

**Comment by BenevidesLecontes** [comment]
@rubensdemelo ok thanks, vou olhar o changelog
