### ISSUE TITLE
Atualizar o telefone para o formato com o 9 adicional

### ISSUE THREAD

**Issue by kristhyanmatos** [flutterbootcamp/brasil_fields#56]

**Comment by rubensdemelo** [comment]
não entendi.

**Comment by kristhyanmatos** [comment]
olá, desculpa não ter me expressado direito.
esse formato: (xx) 9xxxx-xxxx

**Comment by rubensdemelo** [comment]
Ja tem um parametro no formatter para esta situacao

**Comment by kristhyanmatos** [comment]
desculpa, é que não encontrei na doc.

**Comment by rubensdemelo** [comment]
@kristhyanmatos o formatter já está preparado para o nono digito, de forma automatica

![image](https://user-images.githubusercontent.com/1351177/151810145-257caae6-41f7-4e95-b712-8fcf90206bab.png)


![image](https://user-images.githubusercontent.com/1351177/151810203-6846d301-6a2e-4dc5-aa31-9f36fec9407b.png)

**Comment by kristhyanmatos** [comment]
esse certo? => TelefoneInputFormatter()

**Comment by thierryoliveira** [comment]
> esse certo? => TelefoneInputFormatter()

procurei o parâmetro e não encontrei. Poderia me dizer como utilizar o dígito extra no início?
Atualmente estou os formatters assim:
`inputFormatters: [
                      FilteringTextInputFormatter.digitsOnly,
                      TelefoneInputFormatter()
                    ],`

**Comment by tiagoon** [comment]
@thierryoliveira ele identifica de forma automática:
Se o telefone começar com DDD + 9,  teremos DDD + 9 dígitos, se não, teremos DDD + 8 dígitos.
