### ISSUE TITLE
CentavosInputFormatter problema inserir valores

### ISSUE THREAD

**Issue by greboone** [flutterbootcamp/brasil_fields#57]
No formatador de centavos, utilizado da forma mostrada abaixo, obtive o seguinte problema: 
* Ao começar a digitar no campo com o valor 9, e somente 9, o formatador coloca o digito no local errado da string não deixando o usuário apagar o que foi inserido. Só é possível apagar após inserir outro dígito, sendo ele qualquer outro valor.
[Gif demonstrando o problema](https://gifyu.com/image/SzpIk)

```
TextFormField(
  focusNode: _quantityFN, 
  autocorrect: false,
  decoration: InputDecoration(labelText: 'Quantidade'),
  keyboardType: TextInputType.number,
  controller: _quantity,
  inputFormatters: [
    FilteringTextInputFormatter.digitsOnly,
    CentavosInputFormatter(),
  ],
  onChanged: (value) {
    print(value);
  }
),
```

**Comment by greboone** [comment]
Com testes rápidos, alterando na linha 68 a lógica para ` if (numero > 0 && numero <= 9) ` funciona perfeitamente

**Comment by rubensdemelo** [comment]
@greboone vou corrigir este final de semana

**Comment by rubensdemelo** [comment]
corrigido na versao 1.3.1
