### ISSUE TITLE
Formatação double para Real ou Centavos

### ISSUE THREAD

**Issue by gabrielnvo** [flutterbootcamp/brasil_fields#59]
Em casos de cálculo a partir de um valor inserido pelo TextFormField, é necessário realizar a conversão de Real ou Centavos para double, a fim de realizar o cálculo. 

Porém após o cálculo, se quisermos exibir o valor em um novo TextFormField, a única opção oferecida pelo Dart é colocar "valor.toStringAsFixed(2)", por exemplo, pois não existe a formatação para Real ou Centavos novamente, fazendo com que o campo de exibição fique diferente do campo de inserção.

_Exemplo sem formatação:_
![image](https://user-images.githubusercontent.com/98406989/155074739-41df56d1-cf73-43b1-a9c4-4ce61b5dec75.png)

_Exemplo a ser obtido (usei a função "NumberFormat.currency" do package intl):_
![image](https://user-images.githubusercontent.com/98406989/155076678-d09c6839-1c31-4a7e-a9f9-424a6e489e91.png)

**Comment by rubensdemelo** [comment]
@GabrielNarcisioVieira  Tudo bem. Vou pensar numa solucao.
