### ISSUE TITLE
getTextBeforeCursor/getSelectedText on inactive InputConnection

### ISSUE THREAD

**Issue by marcelino-borges** [flutterbootcamp/brasil_fields#6]
Já tinha um form completo e funcionando no meu app em Flutter e tentei usar os formatters dessa biblioteca, porém ao tentar digitar os respectivos dados nos campos de CPF e TELEFONE, respectivamente, fica assim:
![2](https://user-images.githubusercontent.com/33501037/63655224-05d0cf00-c75c-11e9-9528-630e10c64235.jpeg)

Também recebo isso no console:
`getTextBeforeCursor on inactive InputConnection`
`getSelectedText on inactive InputConnection`

E esse é meu input field:

```
TextFormField(
	inputFormatters: inputFormatters,
	onFieldSubmitted: onSumitted,
	textInputAction: textInputAction,
	obscureText: this._obscureText ? (snapshot.data ?? false) : false,
	style: TextStyle(color: Colors.white),
	keyboardType: _textInputType,
	focusNode: focusNode,
	decoration: InputDecoration(
		suffixIcon: this._obscureText
			? IconButton(
				icon: Icon(
					snapshot.data != null
						? (snapshot.data
							? FontAwesomeIcons.eyeSlash
							: FontAwesomeIcons.eye)
						: null,
					color: Colors.white),
				onPressed: () {
				  _signUpBloc.inObscurePasswordText.add(!snapshot.data);
				})
			: null,
		contentPadding:
			EdgeInsets.symmetric(horizontal: 24, vertical: 16),
		filled: true,
		fillColor: Color.fromARGB(80, 255, 255, 255),
		border: OutlineInputBorder(
			borderSide: BorderSide(width: 1, color: Colors.transparent),
			borderRadius:
				const BorderRadius.all(const Radius.circular(35))),
		enabledBorder: OutlineInputBorder(
			borderSide: BorderSide(width: 1, color: Colors.transparent),
			borderRadius:
				const BorderRadius.all(const Radius.circular(35))),
		focusedBorder: OutlineInputBorder(
			borderSide: BorderSide(
				color: Theme.of(context).accentColor, width: 1),
			borderRadius:
				const BorderRadius.all(const Radius.circular(35))),
		errorBorder: OutlineInputBorder(
			borderSide: BorderSide(color: Colors.red, width: 1),
			borderRadius:
				const BorderRadius.all(const Radius.circular(35))),
		focusedErrorBorder: OutlineInputBorder(
			borderSide: BorderSide(color: Colors.red, width: 1),
			borderRadius:
				const BorderRadius.all(const Radius.circular(35))),
		errorStyle: TextStyle(
			fontSize: 14,
			fontWeight: FontWeight.bold,
			color: Colors.red[200]),
		hintText: _hintText,
		hintStyle: TextStyle(color: Colors.white)),
	textCapitalization: _textCapitalization,
	validator: _validator,
	//onSaved: ,
	controller: _fieldController,
);
```

que está dentro de um widget customizado onde recebo diversos parâmetros que setam as configs do meu TextFormField, inclusive a variável "inputFormatters" é uma lista do tipo "TextInputFormatter" que passo. Passei CpfInputFormatter() para o campo de CPF e TelefoneInputFormatter() para o campo de telefone.

Alguém já passou por isso?
Obrigado.

**Comment by rubensdemelo** [comment]
vou tentar simular aqui e te aviso:

Já tentou : `TextFormField(
  inputFormatters: [
    WhitelistingTextInputFormatter.digitsOnly,
    CpfInputFormatter(),
  ],
);`

**Comment by marcelino-borges** [comment]
> vou tentar simular aqui e te aviso:
> 
> Já tentou : `TextFormField( inputFormatters: [ WhitelistingTextInputFormatter.digitsOnly, CpfInputFormatter(), ], );`

Tentei, sim. Quando faço isso, a máscara deixa de aparecer dentro do campo e fica como se não tivesse usando formatter algum. kkk

Obrigado!

**Comment by rubensdemelo** [comment]
@marcelino-borges é um problema com textinputformatter em geral. Já abri uma issue la no repositório do flutter https://github.com/flutter/flutter/issues/39223

**Comment by rubensdemelo** [comment]
https://github.com/flutter/flutter/issues/39047

**Comment by marcelino-borges** [comment]
> @marcelino-borges é um problema com textinputformatter em geral. Já abri uma issue la no repositório do flutter [flutter/flutter#39223](https://github.com/flutter/flutter/issues/39223)

Ahhh, saquei! Que pena! Valeu pela prestatividade!
