### ISSUE TITLE
Erro ao digitar 0 como primeiro dígito do campo

### ISSUE THREAD

**Issue by mateuss-silva** [flutterbootcamp/brasil_fields#65]
No formatador de centavos, quando digita "0" com o campo vazio, uma exception é lançada, mas o comportamento ainda continua consistente se continuar digitando.

```
TextFormField(
  controller: _controller,
  inputFormatters: [
    FilteringTextInputFormatter.digitsOnly,
    CentavosInputFormatter(),
  ],
),
```

**Comment by rubensdemelo** [comment]
O erro está aqui: https://github.com/flutterbootcamp/brasil_fields/blob/c907c83e07e33f6e62232209ba11aad0fa0bdaa6/lib/src/formatters/centavos_input_formatter.dart#L46

Vou ajustar e publicar uma nova versão. Obrigado

**Comment by rubensdemelo** [comment]
Corrigido na v1.4.4. Obrigado.

**Comment by rein4nl1m** [comment]
Bom dia @rubensdemelo 
Utilizando a versão 1.12 da lib, me deparei com um problema relacionado a esse mesmo caso: ao limpar o campo e tentar digitar somente zeros, o cursor trava após a vírgula e não insere os zeros das casas decimais.
Se eu limpo, ele limpa o input inteiro.
Se eu insiro um número maior que zero, ele funciona normalmente.

Não sei se seria o caso de reabrir essa issue, pois vejo que o problema é relacionado.

**Comment by rubensdemelo** [comment]
Preciso simular este comportamento e tentar identificar o erro. Na pagina de exemplo isso tb acontece? Qual a sequencia das teclas?

**Comment by rein4nl1m** [comment]
Não cheguei a testar com a página de exemplo

A sequencia seria:

Backspace (Apagar) > Digitar 0 uma vez > Digtar 0 mais uma vez.
Ao digitar o segundo Zero, ele apaga todo o valor no text field. 
Ao digitar uma terceira vez, ele voltar a exibir "0," somente, e fica nesse loop enquanto não digitar um valor maior que zero.

Pra ajudar a simular melhor, estou utilizando um TextField com essas máscaras aqui:

FilteringTextInputFormatter.digitsOnly,
CentavosInputFormatter(casasDecimais: 2),

**Comment by rubensdemelo** [comment]
Mas isso eh o esperado e seguindo o padrao de alguns bancos (BB, Nubank, C6, etc):

Com valores monetarios, se digitar:
0 = 0
00 = 0
000 = 0
1 = 0,01 centavo
11 = 0,11

**Comment by rein4nl1m** [comment]
No caso, com o CentavosInputFormatter, tá se comportando dessa forma aqui:
0 = 0,
00 = (vazio)
0 = 0,

Segue video do comportamento:
https://github.com/rein4nl1m/firebase_salesforce_app/assets/34170443/c2c2daed-ff4f-49ea-b143-b7a6ddb9f72a

**Comment by rubensdemelo** [comment]
Entao você quer a possibilidade do usuário informar no campo 0,00 ?
