### ISSUE TITLE
Formatação CPF com problema

### ISSUE THREAD

**Issue by harguus** [flutterbootcamp/brasil_fields#66]
Ao digitar o CPF a partir do terceito dígito a mascara coloca pontos enquanto diga repetidamente e não consigo apagar oque foi digitado.

![image](https://user-images.githubusercontent.com/1157913/168825001-eb2d6769-a21c-4bc6-a09d-7b8f04ab164b.png)

Obs: Utilizei outra mascara e funciona normal, mas queria manter só essa pois o da placa funciona perfeitamente.

**Comment by rubensdemelo** [comment]
Voce não deve estar usando o FilteringTextInputFormatter.digitsOnly.

**Comment by harguus** [comment]
> FilteringTextInputFormatter.digitsOnly

Deu certo, Obrigada!
