### ISSUE TITLE
Problema na Placa de veiculo

### ISSUE THREAD

**Issue by rodrigorafaeldamaceno** [flutterbootcamp/brasil_fields#68]
Bom dia, obrigado pelo pacote, é muito útil.

Notei um problema com relação a Placa de veiculo, isso se repete em outros pacotes de mascara também.

Quando troco para o teclado numérico, ele permite add apenas um número e volta para o teclado padrão, sabe se tem alguma solução para isso?

**Comment by rubensdemelo** [comment]
@rodrigorafaeldamaceno Não há solução. Este comportamente é "nativo" do Flutter. E com o `FilteringTextInputFormatter.digitsOnly,`, independente do tipo de teclado, somente números são aceitos.
