### ISSUE TITLE
Outros formatos de data

### ISSUE THREAD

**Issue by lucasbordini** [flutterbootcamp/brasil_fields#77]
É possivel utilizar outros formatos de data ?
apenas dia e mes ou apenas mes e ano ?

**Comment by rubensdemelo** [comment]
Não tem nenhum formatter assim, por enquanto. O que mais se aproxima é o de validade de cartão bancário (MM/AA). Mas posso criar. Quais seriam os formatos ?

DD/MM
MM/AAAA ?

**Comment by lucasbordini** [comment]
Isso, DD/MM e MM/AAAA

**Comment by rubensdemelo** [comment]
O formatter ValidadeCartaoInputFormatter já suporta MM/AAAA ou MM/AA. Vou criar um novo para DD/MM.
