### ISSUE TITLE
Formatter de celular

### ISSUE THREAD

**Issue by cpelegrin** [flutterbootcamp/brasil_fields#8]
Percebi que não formata o número do celular (9 a mais no início).

Também poderiam incluir validadores!

**Comment by cpelegrin** [comment]
achei no código fonte! hahahha

Só falta incluir na documentação.

Obrigado

**Comment by rubensdemelo** [comment]
vou corrigir a documentacao. obrigado @cpelegrin

**Comment by cpelegrin** [comment]
Uma outra coisa que verifiquei, se o 9 está habilitado, mesmo que eu não comece a string com 9, a máscara formata para número de celular.

Obrigado você!

**Comment by rubensdemelo** [comment]
@cpelegrin nova versão para melhorar o uso do nono dígito.
