### ISSUE TITLE
intl: ^0.18.0

### ISSUE THREAD

**Issue by icred-thiago** [flutterbootcamp/brasil_fields#84]
a new version with intl: ^0.18

**Comment by chrystoffer** [comment]
Você pode adicionar no seu pubspec.yaml

dependency_overrides:
  intl: ^0.18.0

**Comment by rubensdemelo** [comment]
vou gerar uma nova versao atualizando esta dependencia

**Comment by rubensdemelo** [comment]
Corrigido na versão 1.10
