### ISSUE TITLE
Moeda converte errado

### ISSUE THREAD

**Issue by marcos93net** [flutterbootcamp/brasil_fields#86]
Olá, coloquei 20000 e está me retornando 2.0.000 no lugar de 20.000
meu código:
TextField(
              controller: value1,
              keyboardType: TextInputType.number,
              inputFormatters: [RealInputFormatter()],
              ),

**Comment by rubensdemelo** [comment]
A sua implementacao esta errada. Veja a documentacao.

**Comment by marcos93net** [comment]
Solved
