### ISSUE TITLE
intl version error

### ISSUE THREAD

**Issue by mirdones** [flutterbootcamp/brasil_fields#88]
I am getting this error:

Because brasil_fields >=1.10.0 depends on intl ^0.18.0 and every version of flutter_localizations from sdk depends on intl 0.17.0, brasil_fields >=1.10.0 is incompatible with flutter_localizations from sdk.
And because firebase_ui_auth 1.4.0 depends on flutter_localizations from sdk and no versions of firebase_ui_auth match >1.4.0 <2.0.0, brasil_fields >=1.10.0 is incompatible with firebase_ui_auth ^1.4.0.
So, because baintec_page depends on both firebase_ui_auth ^1.4.0 and brasil_fields ^1.12.0, version solving failed.
pub get failed (1; So, because baintec_page depends on both firebase_ui_auth ^1.4.0 and brasil_fields ^1.12.0, version solving failed.)

**Comment by rubensdemelo** [comment]
Na versão 1.13 isso está corrigido.

**Comment by mirdones** [comment]
With this update I am getting:

Because brasil_fields >=1.13.0 depends on intl ^0.18.1 and every version of flutter_localizations from sdk depends on intl 0.18.0, brasil_fields >=1.13.0 is incompatible with flutter_localizations from sdk.
And because firebase_ui_auth 1.4.1 depends on flutter_localizations from sdk and no versions of firebase_ui_auth match >1.4.1 <2.0.0, brasil_fields >=1.13.0 is incompatible with firebase_ui_auth ^1.4.1.
So, because baintec_page depends on both firebase_ui_auth ^1.4.1 and brasil_fields ^1.13.0, version solving failed.

**Comment by rubensdemelo** [comment]
atualiza para a versão 1.13.1. 

Como está o flutter_localizations ?
