### ISSUE TITLE
Mask para horario?

### ISSUE THREAD

**Issue by AlexPassos** [flutterbootcamp/brasil_fields#9]
Tem alguma forma de personalizar? Para colocar a mascara de horario?

**Comment by rubensdemelo** [comment]
@AlexPassos até tem. dá pra criar uma máscara sim. obrigado pela sugestao

**Comment by AlexPassos** [comment]
@rubensdemelo Já tem essa opção? Se tiver como fazer?

**Comment by rubensdemelo** [comment]
@AlexPassos ainda não. Mas estes próximos dias eu vou implementar e atualizar o plugin e a documentação

**Comment by rubensdemelo** [comment]
@AlexPassos formatter para hora

https://pub.dev/documentation/brasil_fields/latest/formatter_hora_input_formatter/formatter_hora_input_formatter-library.html
