### ISSUE TITLE
O formatador de centavo está apagando até a vírgula

### ISSUE THREAD

**Issue by ImPabl0** [flutterbootcamp/brasil_fields#90]
Quando o campo está vazio e tento começar inserindo o zero ele quebra e apaga até a vírgula desse jeito:
![image](https://github.com/flutterbootcamp/brasil_fields/assets/83519111/1ffebf9d-296c-401a-8d74-f6b0ec6546e7)

**Comment by rubensdemelo** [comment]
Não entendi onde esta o erro. Pode detalhar um pouco melhor, por favor.
