### ISSUE TITLE
 UtilBrasilFields.obterXXX(valorComErro) esta gerando Exception. Sugiro gerar Null

### ISSUE THREAD

**Issue by catalunha** [flutterbootcamp/brasil_fields#94]
Parabens pelo pacote. Sucesso na caminhada.
Como a utilização dos  UtilBrasilFields.obterXYZ(valorEntrada) é mais dentro dos widgets e caso o valor de `valorEntrada` tenha um valor inconsistente as funções geram uma Exception.

E Exceptions não podem ser tratadas no widgets. Então sugiro o retorno ser Null pois caso o valor de  `valorEntrada` não seja possível ser formatado ele retornaria um Null que seria mais facil tratar no widget.

**Comment by catalunha** [comment]
Só para ressaltar. A entrada e saida devem ser Nulls. Assim a função fica passivel de uso com qq entrada (Null, Incorreta ou correta) gerando uma saida (Null, ou formatada)

**Comment by rubensdemelo** [comment]
@catalunha Obrigado. Este comportamento ja foi discutido no passado. O uso dessa funcao é apenas obter o valor e nao fazer qualquer tipo de validacao. A exception é gerada por um `assert` nas funções, algo bem semelhante ao codigo dentro do proprio Flutter.
