### ISSUE TITLE
CentavosInputFormatter não aceita preço zerado

### ISSUE THREAD

**Issue by luisotavio-dev** [flutterbootcamp/brasil_fields#97]
Ao utilizar o formatter de Centavos, independente se a propriedade "moeda" está true ou false não está permitindo informar um preço zerado. O problema pode ser simulado até mesmo pela página de testes:
https://flutterbootcamp.github.io/brasil_fields/

Por favor, se estiver deixando algo passar me corrija.
Desde já, obrigado.

**Comment by luisotavio-dev** [comment]
Verificando o código fonte, percebi que possui uma instrução para limpar quando for 0 mesmo:

```
// apaga o campo quando os valores forem zero (inteiro e decimais).
if (reais == 0 && int.tryParse(centavos) == 0) {
  return TextEditingValue.empty;
}

// apaga o campo quando novo valor for 0 e o valor anterior tambem era 0.
if (reais == 0 && (oldValue.text == '0,' || oldValue.text == 'R\$ 0,')) {
  return TextEditingValue.empty;
}
```

Queria entender o porquê seria dessa forma. No meu caso estou usando em um sistema comercial onde eu teria vários preços de venda, e alguns deles, caso não trabalhe, poderia ser informado como 0, como preço de atacado ou preço de varejo. 
Vale ressaltar que estou compilando para Desktop e Web.

**Comment by rubensdemelo** [comment]
Oi @luisotavio-dev este é o mesmo padrão utilizados por bancos como o BB e Nubank para lidar com o valor zero.

**Comment by luisotavio-dev** [comment]
Entendido, está ok, obrigado
